#
# Stack relies on the following environment variables to be present:
# - PUBLISHED_PORT
# - GITLAB_INSTANCE_ADDRESS
# - GITLAB_API_TOKEN
#

version: '2.0'

services:
  gitlab-merge-trigger:
    build: .
    restart: always
    ports:
      - $PUBLISHED_PORT:8080
    command:
      -listen=:8080 -url=$GITLAB_INSTANCE_ADDRESS -private-token=$GITLAB_API_TOKEN